config/routes.rb
Rails.application.routes.draw do

  devise_for :models
  # Admin Route
  namespace :admin, path: '/admin' do
    get '/', to: 'index#show', as: 'index'

    # Season Section
    get '/seasons', to: 'seasons#index', as: 'seasons'
    post '/seasons', to: 'seasons#create', as:'new_season'
    get 'seasons/:id', to: 'seasons#show', as: 'season'
    patch 'seasons/:id/update', to:'seasons#update', as: 'update_season'
    patch '/seasons/:id/set_current', to: 'seasons#set_current', as:'set_current_season'
    delete '/seasons/:id/delete', to:'seasons#delete', as:'delete_season'


    # Player Section
    resources :players

    # Roster section
    get '/rosters', to: 'rosters#show', as: 'rosters'
    get '/rosters/:id/manage', to: 'rosters#manage', as: 'manage_roster'
    post 'rosters/add/:season_id/:player_id', to: 'rosters#add', as:'add_roster'
    delete 'rosters/delete/:season_id/:player_id', to: 'rosters#delete', as:'delete_roster'

    # Game/Schedule Section
    post '/games/create', to: 'games#create', as: 'create_game'
    delete '/games/:id/delete', to:'games#delete', as:'delete_game'
    get 'games/:id', to:'games#show', as: 'game'
    get 'games/:id/edit', to:'games#edit', as: 'edit_game'
    patch 'games/:id/update', to:'games#update', as: 'update_game'
    get 'games/:id/migrate_to_stat', to:'games#migrate', as: 'game_stat_migrate'
    post 'games/:id/update_score', to: 'games#update_score', as: 'game_update_score'
    post 'games/:id/update_oppo', to: 'games#update_oppo', as: 'game_update_oppo'

    get 'games/:id/dnp', to: 'games#dnp', as: 'game_dnp'
    get 'adddnp/:game_id/:player_id', to: 'games#dnp_add', as: 'game_add_dnp'
    get 'removednp/:game_id/:player_id', to: 'games#dnp_remove', as: 'game_remove_dnp'

    get 'games/:id/score_only', to: 'games#score_only', as: 'game_score_only'
    post 'games/:id/score_only_update', to: 'games#score_only_update', as: 'game_score_only_update'

    # Action Section
    post '/actions', to: 'actions#create', as: 'create_action'
    get '/actions/quarter_end/:game_id', to: 'actions#quarter_end', as: 'quarter_end'
    delete '/actions/:id', to: 'actions#delete', as: 'delete_action'


    #Action Sequence
    get '/actions/:id/position/:pos_index', to: 'actions#move', as: 'action_move_postion'
  end

  # Design Guide Route
  namespace :design, path: '/design' do
    get '/', to: 'design#about', as: 'about'
    get 'typography', to: 'design#typography', as: 'typography'
    get 'table', to: 'design#table', as: 'table'
    get 'table_example', to: 'design#table_example', as: 'table_example'
    get 'dropdown', to: 'design#dropdown', as: 'dropdown'
    get 'card-panel', to: 'design#card_panel', as: 'card_panel'

    get 'player_card', to: 'design#player_card', as: 'player_card'
    get 'player_header', to: 'design#player_header', as: 'player_header'

    get 'match_card', to: 'design#match_card', as: 'match_card'
    get 'match_header', to: 'design#match_header', as: 'match_header'
    get 'match_stat', to: 'design#match_stat', as: 'match_stat'
    get 'match_boxscore', to: 'design#match_boxscore', as: 'match_boxscore'
    get 'match_playbyplay', to: 'design#match_playbyplay', as: 'match_playbyplay'

    get 'team_header', to: 'design#team_header', as: 'team_header'

    get 'global_nav', to: 'design#global_nav', as: 'global_nav'

  end

  # API Routes
  namespace :api, path: '/api' do
    get 'team', to: 'team#team'

    resources :players, only: [:index, :show]

    resources :seasons, only: [:index, :show]

    resources :games, only: [:index, :show]

    # Video API Routes
    get 'videos', to: 'videos#query'
    post '/videos/post', to: 'videos#post'

  end

  # Video REST API manage
  get '/videos/import', to: 'videos#import', as: 'video_import'
  resources :videos, only: [:index, :show, :create, :update, :destroy]



  # Production Routes
  resources :players, only: [:index, :show]

  resources :games, only: [:show]
  get '/schedules', to: 'gamelist#schedules'
  get '/results', to: 'gamelist#results'


  # Homepage Routes
  root 'team_page#show', as: 'home'

end

app/models/season.rb
class Season < ActiveRecord::Base
  has_many :rosters
  has_many :players, through: :rosters
  has_many :games

  after_initialize {self.name = name.strip.downcase}
  validates :name, presence: true, uniqueness: true

  def set_default_season
    current_season ||= Season.find_by(is_current_season: true)
    unless current_season.blank?
      current_season.update(is_current_season: false)
    end
    unless self.update(is_current_season: true)
      flash[:danger] = self.errors.full_messages[0]
    end
  end

  def self.get_current_season
    Season.find_by(is_current_season: true)
  end

  def recorded_games
    self.games.where(game_record: true).order(gametime: :desc)
  end


end

app/controllers/API/seasons_controller.rb
module API
  class SeasonsController < ApplicationController
    def index
      seasons = Season.all
      render :json => seasons
    end

    def show
      season = Season.find(params[:id])
      render :json => season
    end

    def players
      season = Season.find(params[:id])
      render :json => season.players
    end

    def games
      season = Season.find(params[:id])
      render :json => season.games
    end
  end
end

app/controllers/admin/seasons_controller.rb
module Admin
  class SeasonsController < AdminController

    def index
      @seasons = Season.all.order('start_date')
    end

    def show
      @season = Season.find(params[:id])
      @games = @season.games.order('gametime')
    end

    def create
      unless @season = Season.create(season_params)
        flash[:danger] = @season.errors.messages
      end
      redirect_to(admin_seasons_path)
    end

    def set_current
      @season = Season.find(params[:id])
      @season.set_default_season

      redirect_to(admin_seasons_path)
    end

    def delete
      @season = Season.find(params[:id])
      flash[:success] = @season.name + ' removed'
      @season.destroy
      redirect_to(admin_seasons_path)
    end

    def update
      @season = Season.find(params[:id])
      unless @season.update(season_params)
        flash[:danger] = @season.errors.full_messages[0]
      end
      redirect_to admin_season_path(@season)
    end



    private

    def season_params
      params.require(:season).permit(:name, :start_date)
    end
  end
end

app/views/admin/seasons/index.html.erb
<h1>Season Admin</h1>

<section>
  <h3>Add new Season</h5>
  <%= form_for :season, url: admin_new_season_path do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>

    <%= f.label :start_date %>
    <%= f.date_field :start_date %>

    <%= f.submit("Add new season") %>
  <% end %>
</section>

<section>
  <h3>Season List</h3>
  <ul>
    <% @seasons.each do |season| %>

      <li class="<%= season.is_current_season%>"><%= link_to season.name, admin_season_path(season) %> Start Date:<%= season.start_date %>  CTA: <%= link_to 'delete', admin_delete_season_path(season), method: :delete, data: { confirm: 'Are you sure?' } %> <%= link_to 'set current season', admin_set_current_season_path(season), method: :patch %></li>
    <% end %>
  </ul>
</section>

app/views/admin/seasons/show.html.erb
<h1><%= @season.name %> Management</h1>

<section>
  <h3>Update season info</h3>
  <%= form_for :season, url: admin_update_season_path, method: :patch do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>

    <%= f.label :start_date %>
    <%= f.date_field :start_date %>

    <%= f.submit("Update new season") %>
  <% end %>
</section>
<section>
  <h3>Add New Game</h3>
  <%= form_for :game, url: admin_create_game_path do |f| %>
    <%= f.label :opponent %>

    <%= f.select(:opponent) do %>
      <% opp_array = OPPO_TEAM_ARR.map.with_index { |oppo, index| [oppo[:name], index + 1]} %>
      <%= options_for_select(opp_array) %>
    <% end %>

    <%= f.label :gametime %>
    <%= f.datetime_local_field :gametime %>

    <%= f.hidden_field :season_id, value: @season.id %>

    <%= f.submit("Add") %>
  <% end %>
</section>

<section>
  <h3>Game list</h3>
  <% if @games.length > 0 %>
    <% @games.each_with_index do |game, index| %>
      <div class="season__gamelist-item">
        <div><%= index + 1 %> </div>
        <div><%= link_to 'Track', admin_game_path(game) %></div>
        <div class="team-name"><%= game.opponent_name%></div>
        <div><%=game.gametime %></div>
        <div><%= link_to 'Edit', admin_edit_game_path(game)%></div>
        <div><%= link_to 'Remove', admin_delete_game_path(game), method: :delete, data: { confirm: 'Are you sure?' }%></div>
      </div>
    <% end %>
  <% else %>
    No Game! Please add new one.
  <% end %>
</section>