config/routes.rb
Rails.application.routes.draw do

  devise_for :models
  # Admin Route
  namespace :admin, path: '/admin' do
    get '/', to: 'index#show', as: 'index'

    # Season Section
    get '/seasons', to: 'seasons#index', as: 'seasons'
    post '/seasons', to: 'seasons#create', as:'new_season'
    get 'seasons/:id', to: 'seasons#show', as: 'season'
    patch 'seasons/:id/update', to:'seasons#update', as: 'update_season'
    patch '/seasons/:id/set_current', to: 'seasons#set_current', as:'set_current_season'
    delete '/seasons/:id/delete', to:'seasons#delete', as:'delete_season'


    # Player Section
    resources :players

    # Roster section
    get '/rosters', to: 'rosters#show', as: 'rosters'
    get '/rosters/:id/manage', to: 'rosters#manage', as: 'manage_roster'
    post 'rosters/add/:season_id/:player_id', to: 'rosters#add', as:'add_roster'
    delete 'rosters/delete/:season_id/:player_id', to: 'rosters#delete', as:'delete_roster'

    # Game/Schedule Section
    post '/games/create', to: 'games#create', as: 'create_game'
    delete '/games/:id/delete', to:'games#delete', as:'delete_game'
    get 'games/:id', to:'games#show', as: 'game'
    get 'games/:id/edit', to:'games#edit', as: 'edit_game'
    patch 'games/:id/update', to:'games#update', as: 'update_game'
    get 'games/:id/migrate_to_stat', to:'games#migrate', as: 'game_stat_migrate'
    post 'games/:id/update_score', to: 'games#update_score', as: 'game_update_score'
    post 'games/:id/update_oppo', to: 'games#update_oppo', as: 'game_update_oppo'

    get 'games/:id/dnp', to: 'games#dnp', as: 'game_dnp'
    get 'adddnp/:game_id/:player_id', to: 'games#dnp_add', as: 'game_add_dnp'
    get 'removednp/:game_id/:player_id', to: 'games#dnp_remove', as: 'game_remove_dnp'

    get 'games/:id/score_only', to: 'games#score_only', as: 'game_score_only'
    post 'games/:id/score_only_update', to: 'games#score_only_update', as: 'game_score_only_update'

    # Action Section
    post '/actions', to: 'actions#create', as: 'create_action'
    get '/actions/quarter_end/:game_id', to: 'actions#quarter_end', as: 'quarter_end'
    delete '/actions/:id', to: 'actions#delete', as: 'delete_action'


    #Action Sequence
    get '/actions/:id/position/:pos_index', to: 'actions#move', as: 'action_move_postion'
  end

  # Design Guide Route
  namespace :design, path: '/design' do
    get '/', to: 'design#about', as: 'about'
    get 'typography', to: 'design#typography', as: 'typography'
    get 'table', to: 'design#table', as: 'table'
    get 'table_example', to: 'design#table_example', as: 'table_example'
    get 'dropdown', to: 'design#dropdown', as: 'dropdown'
    get 'card-panel', to: 'design#card_panel', as: 'card_panel'

    get 'player_card', to: 'design#player_card', as: 'player_card'
    get 'player_header', to: 'design#player_header', as: 'player_header'

    get 'match_card', to: 'design#match_card', as: 'match_card'
    get 'match_header', to: 'design#match_header', as: 'match_header'
    get 'match_stat', to: 'design#match_stat', as: 'match_stat'
    get 'match_boxscore', to: 'design#match_boxscore', as: 'match_boxscore'
    get 'match_playbyplay', to: 'design#match_playbyplay', as: 'match_playbyplay'

    get 'team_header', to: 'design#team_header', as: 'team_header'

    get 'global_nav', to: 'design#global_nav', as: 'global_nav'

  end

  # API Routes
  namespace :api, path: '/api' do
    get 'team', to: 'team#team'

    resources :players, only: [:index, :show]

    resources :seasons, only: [:index, :show]

    resources :games, only: [:index, :show]

    # Video API Routes
    get 'videos', to: 'videos#query'
    post '/videos/post', to: 'videos#post'

  end

  # Video REST API manage
  get '/videos/import', to: 'videos#import', as: 'video_import'
  resources :videos, only: [:index, :show, :create, :update, :destroy]



  # Production Routes
  resources :players, only: [:index, :show]

  resources :games, only: [:show]
  get '/schedules', to: 'gamelist#schedules'
  get '/results', to: 'gamelist#results'


  # Homepage Routes
  root 'team_page#show', as: 'home'

end

app/controllers/design/design_controller.rb
module Design
  class DesignController < ApplicationController
    layout 'design_guide'

    def about
    end

    def typography
    end

    def table
    end

    def table_example
    end

    def player_card
    end

    def match_card
    end

    def dropdown
    end

    def match_header
    end

    def match_playbyplay
    end

    def team_header
    end

    def global_nav
    end
  end
end

app/helpers/design_helper.rb
module DesignHelper
  def sidebar_component_class(active_item)
    return 'collapsible-header waves-effect waves-teal active' if ['typography', 'table', 'table_example', 'card_panel', 'dropdown'].include? active_item
    'collapsible-header waves-effect waves-teal'
  end

  def sidebar_match_class(active_item)
    return 'collapsible-header waves-effect waves-teal active' if [ 'match_card', 'match_header', 'match_stat', 'match_boxscore','match_playbyplay'].include? active_item
    'collapsible-header waves-effect waves-teal'
  end

  def sidebar_player_class(active_item)
    return 'collapsible-header waves-effect waves-teal active' if ['player_card', 'player'].include? active_item
    'collapsible-header waves-effect waves-teal'
  end

  def sidebar_team_class(active_item)
    return 'collapsible-header waves-effect waves-teal active' if ['team_header'].include? active_item
    'collapsible-header waves-effect waves-teal'
  end



end

app/views/design/_footer.html.erb
<footer class="page-footer">
  <div class="container">
    <div class="row">
      <div class="col xs12">
        <h5 class="reverse-text-color">Design Guide</h5>
        <p class="grey-text text-lighten-4">This is the design guide for BaStat Project</p>

      </div>
    </div>
  </div>
  <div class="footer-copyright">
    <div class="container">
    © 2014-2016 Xin Liu, All rights reserved.
    <a class="grey-text text-lighten-4 right" href="">MIT License</a>
    </div>
  </div>
</footer>

app/views/design/_header.html.erb
<header>
  <div class="container"><a href="#" data-activates="nav-mobile" class="button-collapse top-nav waves-effect waves-light circle hide-on-large-only"><i class="material-icons">menu</i></a></div>
  <ul id="nav-mobile" class="side-nav fixed">
    <li class="logo">
      <%= image_tag('TeamLogo.jpg')%>
    </li>
    <li class="bold">
      <%= link_to 'About', design_about_path, class: 'waves-effect waves-teal'%>
    </li>
    <li class="no-padding">
      <ul class="collapsible collapsible-accordion">
        <li class="bold">
          <a class="<%= sidebar_component_class(active_item) %>">Components</a>
          <div class="collapsible-body">
            <ul>
              <li <%= 'class=active' if active_item == "typography"%>><%= link_to 'Typography', design_typography_path %></li>
              <li <%= 'class=active' if active_item == "card_panel"%>><%= link_to 'Card Panel', design_card_panel_path %></li>
              <li <%= 'class=active' if active_item == "table"%>><%= link_to 'Table', design_table_path %></li>
              <li <%= 'class=active' if active_item == "table_example"%>><%= link_to 'Table Example', design_table_example_path %></li>
              <li <%= 'class=active' if active_item == "dropdown"%>><%= link_to 'Dropdown', design_dropdown_path %></li>

            </ul>
          </div>
        </li>
        <li class="bold">
          <a class="<%= sidebar_match_class(active_item) %>">Match</a>
          <div class="collapsible-body">
            <ul>
              <li <%= 'class=active' if active_item == "match_card"%>><%= link_to 'Match Cards', design_match_card_path %></li>
              <li <%= 'class=active' if active_item == "match_header"%>><%= link_to 'Match Header', design_match_header_path %></li>
              <li <%= 'class=active' if active_item == "match_stat"%>><%= link_to 'Match Stat', design_match_stat_path %></li>
              <li <%= 'class=active' if active_item == "match_boxscore"%>><%= link_to 'Match Boxscore', design_match_boxscore_path %></li>
              <li <%= 'class=active' if active_item == "match_playbyplay"%>><%= link_to 'Match PlayByPlay', design_match_playbyplay_path %></li>

            </ul>
          </div>
        </li>
        <li class="bold"><a class="<%= sidebar_player_class(active_item) %>">Player</a>
          <div class="collapsible-body">
            <ul>
              <li <%= 'class=active' if active_item == "player_card"%>><%= link_to 'Player Cards', design_player_card_path %></li>
              <li <%= 'class=active' if active_item == "player_header"%>><%= link_to 'Player Header', design_player_header_path %></li>
            </ul>
          </div>
        </li>
        <li class="bold"><a class="<%= sidebar_team_class(active_item) %>">Team</a>
          <div class="collapsible-body">
            <ul>
              <li <%= 'class=active' if active_item == "team_header"%>><%= link_to 'Team Header', design_team_header_path %></li>
            </ul>
          </div>
        </li>
      </ul>
    </li>
    <li class="bold"><%= link_to 'Global Nav', design_global_nav_path, class: "waves-teal waves-teal" %></li>
  </ul>
</header>

app/views/design/card.html.erb
<div class="section title-section" id="index-banner">
    <div class="container">
        <div class="row">
            <div class="col s12">
                <h1 class="white-text center-on-small-only">Cards</h1>
            </div>
        </div>
    </div>
</div>

<div class="container">
    <div class="row">
        <div class="col s12 m9 l10">
          <!-- Basic Cards Section-->
          <div id="basic" class="section scrollspy">
            <h2 class="header">Basic Card</h2>
            <div class="row">
              <div class="col s12 m6">
                <!-- Basic Card -->
                <div class="card grey darken-2">
                  <div class="card-content white-text">
                    <span class="card-title">Card Title</span>
                    <p>I am a very simple card. I am good at containing small bits of information. I am convenient because I require little markup to use effectively.</p>
                  </div>
                  <div class="card-action">
                    <a href="#">This is a link</a>
                    <a href="#">This is a link</a>
                  </div>
                </div>
              </div>

                <div class="col s12">
                  <br>
                  <pre class="language-html">
  &lt;div class="row">
    &lt;div class="col s12 m6">
      &lt;div class="card blue-grey darken-1">
        &lt;div class="card-content white-text">
          &lt;span class="card-title">Card Title&lt;/span>
          &lt;p>I am a very simple card. I am good at containing small bits of information.
          I am convenient because I require little markup to use effectively.&lt;/p>
        &lt;/div>
        &lt;div class="card-action">
          &lt;a href="#">This is a link&lt;/a>
          &lt;a href="#">This is a link&lt;/a>
        &lt;/div>
      &lt;/div>
    &lt;/div>
  &lt;/div>
                </pre>
              </div>
            </div>
          </div><%# End of section %>

          <div id="image-card" class="section scrollspy">
            <h2 class="header">Image Player Card</h2>
            <div class="card-panel">
              <div class="card player-card player-card-image" style="max-width:200px;">
                <div class="aspect-content">
                  <div class="player-image waves-effect waves-block waves-light">
                    <%= image_tag('design_guide/player_image.png', class: 'activator') %>
                  </div>
                </div>

                <div class="card-reveal grey lighten-3">
                  <span class="card-title">21<i class="fa fa-times-circle right"></i></span>
                  <div class="player-name">Jimmy Bulter</div>
                  <div class='player-position'>Center</div>
                  <p>Here is some more information about this product that is only revealed once clicked on.</p>
                </div>
              </div>
            </div>
            <!-- Player Basic Card HTML -->
            <pre class="language-html">
  &lt;div class="card player-card-image" style="max-width:200px;">
    &lt;div class="aspect-content">
      &lt;div class="player-image waves-effect waves-block waves-light">
        &lt;img/>
      &lt;/div>
    &lt;/div>

    &lt;div class="card-reveal grey lighten-3">
      &lt;span class="card-title">21&lt;i class="fa fa-times-circle right">&lt;/i>&lt;/span>
      &lt;div class="player-name">Jimmy Bulter&lt;/div>
      &lt;div class='player-position'>Center&lt;/div>
      &lt;p>Here is some more information about this product that is only revealed once clicked on.&lt;/p>
    &lt;/div>
  &lt;/div>
            </pre>
          </div><%# End of section %>


          <div id="stacked-card" class="section scrollspy">
            <h2 class="header">Stacked Player Card</h2>
            <div class="card-panel">
              <div class="card player-card player-card-stacked responsive" style="max-width:250px;">
                <div class="aspect-content">
                  <div class="player-image waves-effect waves-block waves-light">
                    <%= image_tag('design_guide/player_image.png', class: 'activator') %>
                  </div>
                </div>
                <div class="card-content grey lighten-3">
                  <div class="row no-margin">
                    <div class="col s12 m9">
                      <div class="player-name activator semi-bold">Jimmy Bulter</div>
                      <div class='player-position activator hide-on-med-and-up'>21</div>
                      <div class='player-position activator'>Center</div>
                    </div>
                    <div class="col m3 center hide-on-small-only">
                      <span class="player-number bold activator">21</span>
                    </div>
                  </div>
                </div>
                <div class="card-reveal grey lighten-3">
                  <span class="card-title">Jimmy Bulter<i class="fa fa-times-circle right"></i></span>
                  <div class='player-position'>Center - 21</div>
                  <p>Here is some more information about this product that is only revealed once clicked on.</p>
                </div>
              </div>
            </div>
            <!-- Player Basic Card HTML -->
            <pre class="language-html">
  &lt;div class="card player-card-stacked">
    &lt;div class="aspect-content">
      &lt;div class="player-image waves-effect waves-block waves-light">
        &lt;img/>
      &lt;/div>
    &lt;/div>
    &lt;div class="card-content grey lighten-3">
      &lt;div class="row no-margin">
        &lt;div class="col s12 m9">
          &lt;div class="player-name activator semi-bold">Jimmy Bulter&lt;/div>
          &lt;div class='player-position activator '>Center&lt;/div>
        &lt;/div>
        &lt;div class="col m3 center hide-on-small-only">
          &lt;span class="player-number bold activator ">21&lt;/span>
        &lt;/div>
      &lt;/div>
    &lt;/div>
    &lt;div class="card-reveal grey lighten-3">
      &lt;span class="card-title">Jimmy Bulter&lt;i class="fa fa-times-circle right">&lt;/i>&lt;/span>
      &lt;div class='player-position'>Center - 21&lt;/div>
      &lt;p>Here is some more information about this product that is only revealed once clicked on.&lt;/p>
    &lt;/div>
  &lt;/div>
            </pre>
          </div><%# End of section %>

          <div id="horizontal-card" class="section scrollspy">
            <h2 class="header">Horizontal Player Card</h2>
            <div class="card-panel">
              <div class="card player-card player-card-horizontal responsive" style="max-width: 60%;">
                <div class="aspect-content">
                  <div class="player-image waves-effect waves-block waves-light">
                    <%= image_tag('design_guide/player_image.png', class: 'activator') %>
                  </div>
                </div>
                <div class="card-content grey lighten-3">
                  <div class="row no-margin">
                    <div class="col s12 hide-on-small-only">
                      <span class="player-number bold activator">21</span>
                    </div>
                    <div class="col s12">
                      <div class="player-name activator semi-bold">Jimmy Bulter</div>
                      <div class='player-position activator hide-on-med-and-up'>21</div>
                      <div class='player-position activator'>Center</div>
                    </div>

                  </div>
                </div>
                <div class="card-reveal grey lighten-3">
                  <span class="card-title">Jimmy Bulter<i class="fa fa-times-circle right"></i></span>
                  <div class='player-position'>Center - 21</div>
                  <p>Here is some more information about this product that is only revealed once clicked on.</p>
                </div>
              </div>
            </div>
            <!-- Player Basic Card HTML -->
            <pre class="language-html">
  &lt;div class="card player-card-stacked">
    &lt;div class="aspect-content">
      &lt;div class="player-image waves-effect waves-block waves-light">
        &lt;img/>
      &lt;/div>
    &lt;/div>
    &lt;div class="card-content grey lighten-3">
      &lt;div class="row no-margin">
        &lt;div class="col s12 hide-on-small-only">
          &lt;span class="player-number bold activator ">21&lt;/span>
        &lt;/div>
        &lt;div class="col s12">
          &lt;div class="player-name activator semi-bold">Jimmy Bulter&lt;/div>
          &lt;div class='player-position activator hide-on-med-and-up'>21&lt;/div>
          &lt;div class='player-position activator '>Center&lt;/div>
        &lt;/div>
      &lt;/div>
    &lt;/div>
    &lt;div class="card-reveal grey lighten-3">
      &lt;span class="card-title">Jimmy Bulter&lt;i class="fa fa-times-circle right">&lt;/i>&lt;/span>
      &lt;div class='player-position'>Center - 21&lt;/div>
      &lt;p>Here is some more information about this product that is only revealed once clicked on.&lt;/p>
    &lt;/div>
  &lt;/div>
            </pre>
          </div><%# End of section %>



        </div>
        <div class="col hide-on-small-only m3 l2">
            <ul class="section table-of-contents">
                <li><a href="#section-roboto">Roboto</a></li>
                <li><a href="#section-header">Header</a></li>
                <li><a href="#section-paragraph">Paragraph</a></li>
                <li><a href="#section-blockquotes">Blockquotes</a></li>
                <li><a href="#">List</a></li>
                <li><a href="#">Inline text style</a></li>
                <li><a href="#">Transformation classes</a></li>
                <li><a href="#">Alignment classes</a></li>
                <li><a href="#">Address</a></li>
            </ul>
        </div>
    </div>
</div>

app/views/design/match_card.html.erb
<div class="section title-section" id="index-banner">
    <div class="container">
        <div class="row">
            <div class="col xs12">
                <h1 class="reverse-text-color center-on-small-only">Match Cards</h1>
            </div>
        </div>
    </div>
</div>

<div class="container">
    <div class="row">
        <div class="col xs12 m9 l10">
          <%# Schedule Match Card %>
          <div id="schedule-match-card" class="section scrollspy">
            <h2 class="header">Schedule Match Card</h2>
            <div class="card-panel">
              <div class="card horizontal match-card match-card-schedule">
                <div class="aspect-content">
                  <div class="team-logo">
                    <%= image_tag('design_guide/team_logo.svg') %>
                  </div>
                </div>
                <div class="card-stacked">
                  <div class="card-content">
                    <h3 class='no-margin margin-bottom'>Detroit Pistons</h3>
                    <p><strong>10:30 AM, 10/27/2016</strong></p>
                    <p>Stadium Address</p>

                  </div>
                  <div class="card-action">
                    <a href="#">FULL GAME INFO</a>
                    <br class="hide-on-med-and-up">
                    <a href="#">ADD TO CALENDER</a>
                  </div>
                </div>
              </div>
            </div>
            <!-- Player Basic Card HTML -->
            <pre class="language-html">
  &lt;div class="card horizontal match-card match-card-schedule">
    &lt;div class="aspect-content">
      &lt;div class="team-logo">
        &lt;img>
      &lt;/div>
    &lt;/div>
    &lt;div class="card-stacked">
      &lt;div class="card-content">
        &lt;h3 class='no-margin margin-bottom'>Detroit Pistons&lt;/h3>
        &lt;p>&lt;strong>10:30 AM, 10/27/2016&lt;/strong>&lt;/p>
        &lt;p>Stadium Address&lt;/p>

      &lt;/div>
      &lt;div class="card-action">
        &lt;a href="#">FULL GAME INFO&lt;/a>
        &lt;br class="hide-on-med-and-up">
        &lt;a href="#">ADD TO CALENDER&lt;/a>
      &lt;/div>
    &lt;/div>
  &lt;/div>
            </pre>
          </div><%# End of section %>


          <%# Match Card Simple Result %>
          <div id="match-card-simple-result" class="section scrollspy">
            <h2 class="header">Match Card - Simple Result</h2>
            <div class="card-panel">
              <div class="card horizontal match-card match-card-result-simple">
                <div class="aspect-content">
                  <div class="team-logo">
                    <%= image_tag('design_guide/team_logo.svg') %>
                  </div>
                </div>
                <div class="card-stacked">
                  <div class="card-content">
                    <h5 class='display-inline'>Detroit Pistons</h5>
                    <br class="hide-on-med-and-up">
                    <span>10/05/2016</span>
                    <h2> W 45 - 44</h2>
                  </div>
                  <div class="card-action">
                    <a href="#">FULL GAME INFO</a>
                  </div>
                </div>
              </div>
            </div>
            <!-- Match Card Simple Result HTML -->
            <pre class="language-html">
  &lt;div class="card horizontal match-card match-card-result-simple">
    &lt;div class="aspect-content">
      &lt;div class="team-logo">
        &lt;img>
      &lt;/div>
    &lt;/div>
    &lt;div class="card-stacked">
      &lt;div class="card-content">
        &lt;h5 class='display-inline'>Detroit Pistons&lt;/h5>
        &lt;br class="hide-on-med-and-up">
        &lt;span>10/05/2016&lt;/span>
        &lt;h2> W 45 - 44&lt;/h2>
      &lt;/div>
      &lt;div class="card-action">
        &lt;a href="#">FULL GAME INFO&lt;/a>
      &lt;/div>
    &lt;/div>
  &lt;/div>
            </pre>
          </div><%# End of section %>



          <%# Match Card Detail Result %>
          <div id="match-card-detail-result" class="section scrollspy">
            <h2 class="header">Match Card - Detail Result</h2>
            <div class="card-panel">
              <div class="card horizontal match-card match-card-result-detail">
                <div class="aspect-content">
                  <div class="team-logo">
                    <%= image_tag('design_guide/team_logo.svg') %>
                  </div>
                </div>
                <div class="card-stacked">
                  <div class="card-content">
                    <div class="col s6 no-padding">
                      <h5 class='display-inline'>Detroit Pistons, 10/05</h5>
                      <h4 class='no-margin'> W 45 - 44</h4>
                      <div>
                        <table>
                          <thead>
                            <td></td>
                            <td>1</td>
                            <td>2</td>
                            <td>3</td>
                            <td>4</td>
                            <td></td>
                          </thead>
                          <tr>
                            <td>LSJ</td>
                            <td>0</td>
                            <td>0</td>
                            <td>0</td>
                            <td>0</td>
                            <td>0</td>
                          </tr>
                          <tr>
                            <td>OPPO</td>
                            <td>0</td>
                            <td>0</td>
                            <td>0</td>
                            <td>0</td>
                            <td>0</td>
                          </tr>
                        </table>
                      </div>
                    </div>
                    <div class="col s6 no-padding">
                      3 People
                    </div>
                  </div>
                  <div class="card-action">
                    <a href="#">FULL GAME INFO</a>
                  </div>
                </div>
              </div>
            </div>
            <!-- Match Card Simple Result HTML -->
            <pre class="language-html">
  &lt;div class="card horizontal match-card match-card-result-simple">
    &lt;div class="aspect-content">
      &lt;div class="team-logo">
        &lt;img>
      &lt;/div>
    &lt;/div>
    &lt;div class="card-stacked">
      &lt;div class="card-content">
        &lt;h5 class='no-margin margin-bottom display-inline'>Detroit Pistons&lt;/h5>
        &lt;br class="hide-on-med-and-up">
        &lt;span>10/05/2016&lt;/span>
        &lt;h2> W 45 - 44&lt;/h2>
      &lt;/div>
      &lt;div class="card-action">
        &lt;a href="#">FULL GAME INFO&lt;/a>
      &lt;/div>
    &lt;/div>
  &lt;/div>
            </pre>
          </div><%# End of section %>

        </div>
        <div class="col hide-on-small-and-down m3 l2">
            <ul class="section table-of-contents">
                <li><a href="#section-roboto">Schedule Match Card</a></li>
                <li><a href="#section-header">Result Match Card Simple</a></li>
                <li><a href="#section-paragraph">Result Match Card detailed</a></li>
                <li><a href="#section-blockquotes">Blockquotes</a></li>
                <li><a href="#">List</a></li>
                <li><a href="#">Inline text style</a></li>
                <li><a href="#">Transformation classes</a></li>
                <li><a href="#">Alignment classes</a></li>
                <li><a href="#">Address</a></li>
            </ul>
        </div>
    </div>
</div>

app/views/design/typography.html.erb
<div class="section title-section" id="index-banner">
    <div class="container">
        <div class="row">
            <div class="col xs12">
                <h1 class="reverse-text-color center-on-small-only">Typography</h1>
            </div>
        </div>
    </div>
</div>

<div class="container">
    <div class="row">
        <div class="col xs12 m9 l10">

          <div id="section-roboto" class="section scrollspy">
            <h2>Roboto</h2>
            <div>
              The standard font Material Design uses is Roboto. Roboto fonts will be downloaded from Google CDN.
              <pre class="language-css">$roboto-font-path: "fonts/roboto/" !default;</pre>
            </div>
            <div>
              Font weight 300 is default across the site.
              <div class="card-panel">
                <p class="font-weight-normal">Font Weight : 300</p>
                <p class="font-weight-semi-bold">Font Weight : 400</p>
                <p class="font-weight-bold">Font Weight : 700</p>
              </div>
            </div>
          </div><%# End Section %>

          <div id="section-header" class="section margin-top-lg">
            <h2>Header</h2>
            <div>
              <p>6 header tags different sizes.</p>
              <p>Margin is defined as <code class="language-markup">margin: ($fontsize / 2) 0 ($fontsize / 2.5) 0;</code></p>
              <p>Line height is 1.1</p>
              <div class="card-panel">
                <h1>Heading h1</h1>
                <h2>Heading h2</h2>
                <h3>Heading h3</h3>
                <h4>Heading h4</h4>
                <h5>Heading h5</h5>
                <h6>Heading h6</h6>
                <p>Normal Text</p>
              </div>

            </div>
          </div><%# End Section %>

          <div id="section-paragraph" class="section margin-top-lg">
            <h2>Paragraph</h2>
            <div>
              Global default font-size is 14px, with a line-height of 1.428. This is applied to the <code class="language-markup">body</code> and all paragraphs. In addition, <code class="language-markup">p</code> (paragraphs) receive a bottom margin of half their computed line-height (10px by default).
              <div class="card-panel">
                <p>
                  Nullam quis risus eget urna mollis ornare vel eu leo. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nullam id dolor id nibh ultricies vehicula.
                </p>
                <p>
                  Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec ullamcorper nulla non metus auctor fringilla. Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Donec ullamcorper nulla non metus auctor fringilla.
                </p>
                <p>
                  Maecenas sed diam eget risus varius blandit sit amet non magna. Donec id elit non mi porta gravida at eget metus. Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit
                </p>
              </div>
              <pre class="language-html">
&lt;p>
  This is a paragraph.
&lt;/p>
              </pre>

            </div>
          </div><%# End Section %>

          <div id="section-blockquotes" class="section margin-top-lg">
            <h2 class="header">Blockquotes</h2>
            <p>
              Blockquotes are mainly used to give emphasis to a quote or citation.
              </p>
            <blockquote>
              This is an example quotation that uses the blockquote tag.
              <br>Here is another line to make it look bigger.
            </blockquote>
            <pre class="language-html">
&lt;blockquote>
  This is an example quotation that uses the blockquote tag.
&lt;/blockquote>
            </pre>
          </div><%# End Section %>



        </div>
        <div class="col hide-on-small-and-down m3 l2">
            <ul class="section table-of-contents">
                <li><a href="#section-roboto">Roboto</a></li>
                <li><a href="#section-header">Header</a></li>
                <li><a href="#section-paragraph">Paragraph</a></li>
                <li><a href="#section-blockquotes">Blockquotes</a></li>
                <li><a href="#">List</a></li>
                <li><a href="#">Inline text style</a></li>
                <li><a href="#">Transformation classes</a></li>
                <li><a href="#">Alignment classes</a></li>
                <li><a href="#">Address</a></li>
            </ul>
        </div>
    </div>
</div>