config/routes.rb
Rails.application.routes.draw do

  devise_for :models
  # Admin Route
  namespace :admin, path: '/admin' do
    get '/', to: 'index#show', as: 'index'

    # Season Section
    get '/seasons', to: 'seasons#index', as: 'seasons'
    post '/seasons', to: 'seasons#create', as:'new_season'
    get 'seasons/:id', to: 'seasons#show', as: 'season'
    patch 'seasons/:id/update', to:'seasons#update', as: 'update_season'
    patch '/seasons/:id/set_current', to: 'seasons#set_current', as:'set_current_season'
    delete '/seasons/:id/delete', to:'seasons#delete', as:'delete_season'


    # Player Section
    resources :players

    # Roster section
    get '/rosters', to: 'rosters#show', as: 'rosters'
    get '/rosters/:id/manage', to: 'rosters#manage', as: 'manage_roster'
    post 'rosters/add/:season_id/:player_id', to: 'rosters#add', as:'add_roster'
    delete 'rosters/delete/:season_id/:player_id', to: 'rosters#delete', as:'delete_roster'

    # Game/Schedule Section
    post '/games/create', to: 'games#create', as: 'create_game'
    delete '/games/:id/delete', to:'games#delete', as:'delete_game'
    get 'games/:id', to:'games#show', as: 'game'
    get 'games/:id/edit', to:'games#edit', as: 'edit_game'
    patch 'games/:id/update', to:'games#update', as: 'update_game'
    get 'games/:id/migrate_to_stat', to:'games#migrate', as: 'game_stat_migrate'
    post 'games/:id/update_score', to: 'games#update_score', as: 'game_update_score'
    post 'games/:id/update_oppo', to: 'games#update_oppo', as: 'game_update_oppo'

    get 'games/:id/dnp', to: 'games#dnp', as: 'game_dnp'
    get 'adddnp/:game_id/:player_id', to: 'games#dnp_add', as: 'game_add_dnp'
    get 'removednp/:game_id/:player_id', to: 'games#dnp_remove', as: 'game_remove_dnp'

    get 'games/:id/score_only', to: 'games#score_only', as: 'game_score_only'
    post 'games/:id/score_only_update', to: 'games#score_only_update', as: 'game_score_only_update'

    # Action Section
    post '/actions', to: 'actions#create', as: 'create_action'
    get '/actions/quarter_end/:game_id', to: 'actions#quarter_end', as: 'quarter_end'
    delete '/actions/:id', to: 'actions#delete', as: 'delete_action'


    #Action Sequence
    get '/actions/:id/position/:pos_index', to: 'actions#move', as: 'action_move_postion'
  end

  # Design Guide Route
  namespace :design, path: '/design' do
    get '/', to: 'design#about', as: 'about'
    get 'typography', to: 'design#typography', as: 'typography'
    get 'table', to: 'design#table', as: 'table'
    get 'table_example', to: 'design#table_example', as: 'table_example'
    get 'dropdown', to: 'design#dropdown', as: 'dropdown'
    get 'card-panel', to: 'design#card_panel', as: 'card_panel'

    get 'player_card', to: 'design#player_card', as: 'player_card'
    get 'player_header', to: 'design#player_header', as: 'player_header'

    get 'match_card', to: 'design#match_card', as: 'match_card'
    get 'match_header', to: 'design#match_header', as: 'match_header'
    get 'match_stat', to: 'design#match_stat', as: 'match_stat'
    get 'match_boxscore', to: 'design#match_boxscore', as: 'match_boxscore'
    get 'match_playbyplay', to: 'design#match_playbyplay', as: 'match_playbyplay'

    get 'team_header', to: 'design#team_header', as: 'team_header'

    get 'global_nav', to: 'design#global_nav', as: 'global_nav'

  end

  # API Routes
  namespace :api, path: '/api' do
    get 'team', to: 'team#team'

    resources :players, only: [:index, :show]

    resources :seasons, only: [:index, :show]

    resources :games, only: [:index, :show]

    # Video API Routes
    get 'videos', to: 'videos#query'
    post '/videos/post', to: 'videos#post'

  end

  # Video REST API manage
  get '/videos/import', to: 'videos#import', as: 'video_import'
  resources :videos, only: [:index, :show, :create, :update, :destroy]



  # Production Routes
  resources :players, only: [:index, :show]

  resources :games, only: [:show]
  get '/schedules', to: 'gamelist#schedules'
  get '/results', to: 'gamelist#results'


  # Homepage Routes
  root 'team_page#show', as: 'home'

end

app/models/game.rb
class Game < ActiveRecord::Base

  include GameConcern

  belongs_to :season
  has_one :team_stat
  has_one :oppo_team_stat
  has_one :score
  has_many :actions
  has_many :player_stats
  has_many :players, through: :season

  validates :gametime, presence: true

  def self.schedule_game(season_id = nil)
    Game.order("gametime").where('gametime > ?', DateTime.now.beginning_of_day)
  end

  def self.untrack_game
    Game.where('gametime < ?', DateTime.now.beginning_of_day).where(game_record: false)
  end

  def self.result_game(season_id = nil)
    if season_id.blank?
      Game.order("gametime DESC").where('gametime <= ?', DateTime.now.end_of_day).where(game_record: true)
    else
      Game.order("gametime DESC").where('gametime <= ?', DateTime.now.end_of_day).where(game_record: true, season_id: season_id)
    end

  end

  def self.next_game
    Game.order("gametime").find_by('gametime > ? AND game_record = ?', DateTime.now.beginning_of_day ,false)
  end

  def self.last_game
    Game.order("gametime DESC").find_by('gametime < ? AND game_record = ?', DateTime.now.beginning_of_day, true)
  end

  def init_stat_obj
    TeamStat.create(game: self)
    OppoTeamStat.create(game: self)
  end

  def init_score_obj
    Score.create(game: self)
  end

  def win_or_lose
    #return W or L
    score ||= self.score
    return score.point_total > score.point_op_total ? 'W' : 'L'
  end

  def team
    Team.new
  end

  def find_player_stat_by_player(player)
    @player_stat ||= self.player_stats.find_by(player: player)
  end

  def get_stats_top_player
    # points, rebs, assits
    stats = self.player_stats.where(dnp: false)
    return Hash.new if stats.length == 0 
    {
      point: get_max_stats(stats, 'point'),
      ast: get_max_stats(stats, 'ast'),
      reb: get_max_stats(stats, 'reb')
    }
  end

  def migrate
    # Update team stat, oppo team stat, players_stat
    # Get all actions
    @action_collection = self.actions
    # New team stat obj
    @new_team_stat = TeamStat.new
    @new_oppo_team_stat = OppoTeamStat.new
    # New player stat obj
    @new_player_stats = {}
    self.players.each do |player|
      @new_player_stats[player.id] = PlayerStat.new()
    end
    #migrate data to new obj
    @action_collection.each do |action|
      @new_team_stat.update_from_one_action(action) unless [OPPO_TEAM_ID, NULL_PLAYER_ID].include? action.player_id
      @new_oppo_team_stat.update_from_one_action(action) if action.player_id == OPPO_TEAM_ID
      @new_player_stats[action.player_id].update_from_one_action(action) unless [OPPO_TEAM_ID, NULL_PLAYER_ID, TEAM_ID].include? action.player_id

    end

    # Save obj to db
    team_flag = self.team_stat.update(@new_team_stat.attributes.except("id", "game_id", "created_at", "updated_at"))
    opp_team_flag = self.oppo_team_stat.update(@new_oppo_team_stat.attributes.except("id", "game_id", "created_at", "updated_at"))
    player_flag = true
    self.players.each do |player|
      player_flag &&= PlayerStat.find_or_create_by({game: self, player: player}).update(@new_player_stats[player.id].attributes.except("id", "game_id", "player_id","created_at", "updated_at"))
    end

    return team_flag && player_flag

  end

  def finish_recording
    self.update(game_record: true)
  end

  def opponent_name
    if self.opponent.to_i == 0
      self.opponent
    else
      OPPO_TEAM_ARR[self.opponent.to_i - 1][:name]
    end
  end

  def opponent_shortname
    unless self.opponent.to_i == 0
      OPPO_TEAM_ARR[self.opponent.to_i - 1][:shortname]
    else
      self.opponent[0..2].upcase
    end
  end

  def opponent_image
    unless self.opponent.to_i == 0
      image_name = OPPO_TEAM_ARR[self.opponent.to_i - 1][:logo]
      if image_name.length == 0
        TEAM_OPPO_LOGO_DEFAULT
      else
        'opponents/' + image_name
      end
    else
      TEAM_OPPO_LOGO_DEFAULT
    end
  end

  def opponent_image?
    return false if self.opponent.to_i == 0
    return OPPO_TEAM_ARR[self.opponent.to_i - 1][:logo].length != 0
  end

end

app/controllers/API/games_controller.rb
module API
  class GamesController < ApplicationController
    def index
      if params.has_key?(:type) && params[:type] == GAME_TYPE_SCHEDULE
        games = Game.schedule_game
        render :json => games, include:['season']
      elsif params.has_key?(:type) && params[:type] == GAME_TYPE_RESULT
        games = Game.result_game
        render :json => games, include:['players','season','team_stat','oppo_team_stat','score','actions','player_stats']
      elsif params.has_key?(:type) && params[:type] == GAME_TYPE_UNTRACK
        games = Game.untrack_game
        render :json => games, include:['players','season']
      else
        games = Game.all
        render :json => games, include:['players','season']
      end
    end

    def show
      game = Game.find(params[:id])
      render :json => game
    end

  end
end

app/controllers/admin/games_controller.rb
module Admin
  class GamesController < AdminController

    def show
      @game = Game.find(params[:id])
      @player_collection = @game.players
      @action_list = Action.where(game: @game).order('position')
      @score = Score.find_by(game: @game)

    end

    def edit
        @game = Game.find(params[:id])
    end

    def dnp
      @game = Game.find(params[:id])
      @ingame = PlayerStat.where(game_id: params[:id], dnp: false)
      @outgame = PlayerStat.where(game_id: params[:id], dnp: true)
    end

    def dnp_add
      playerstat = PlayerStat.find_by(player_id: params[:player_id], game_id: params[:game_id])
      playerstat.update_dnp(true)
      redirect_to admin_game_dnp_path(playerstat.game_id)
    end

    def dnp_remove
      playerstat = PlayerStat.find_by(player_id: params[:player_id], game_id: params[:game_id])
      playerstat.update_dnp(false)
      redirect_to admin_game_dnp_path(playerstat.game_id)
    end

    def score_only
      @playerstats = PlayerStat.where(game_id: params[:id])
    end

    def score_only_update
      if params["score"]
        if params["score_only_checkbox"] && params["score_only_checkbox"] == 'on'
          params["score"].each do |score|
            PlayerStat.find_by(player_id: score[0].to_i, game_id: params[:id].to_i).update_score_only(score[1].to_i)
          end
        else
          params["score"].each do |score|
            PlayerStat.find_by(player_id: score[0].to_i, game_id: params[:id].to_i).reset_score_only
          end
        end

        flash[:success] = "Update Successful!"
      else
        flash[:danger] =" Update Fail"
      end
      redirect_to admin_game_score_only_path(params[:id])
    end

    def create
      unless @game = Game.create(game_params)
        flash[:danger] = @game.errors.messages[0]
      end
      @game.init_stat_obj
      @game.init_score_obj
      redirect_to admin_season_path(@game.season)
    end

    def delete
      @game = Game.find(params[:id])
      @game.destroy

      redirect_to admin_season_path(@game.season)
    end

    def migrate
      @game = Game.find(params[:id])
      if @game.migrate
        flash[:success] = 'Migration Done'
      else
        flash[:danger] = 'Migration Failed'
      end
      redirect_to admin_game_path(@game)
    end

    def update_score
      sparams = score_params
      sparams[:point_total] = sparams[:point_q1].to_i + sparams[:point_q2].to_i + sparams[:point_q3].to_i + sparams[:point_q4].to_i
      sparams[:point_op_total] = sparams[:point_op_q1].to_i + sparams[:point_op_q2].to_i + sparams[:point_op_q3].to_i + sparams[:point_op_q4].to_i
      score = Score.find_by(game_id: params[:id])
      score.update(sparams)
      redirect_to admin_game_path(params[:id])
    end

    def update_oppo
      oparams = oppo_params
      game = Game.find(params[:id])
      game.update(oparams)
      redirect_to admin_game_path(params[:id])
    end

    def update
      oparams = game_params
      game = Game.find(params[:id])
      game.update(oparams)
      redirect_to admin_game_path(params[:id])
    end

    private

    def game_params
      params.require(:game).permit(:opponent,:gametime,:season_id)
    end

    def score_params
      params.require(:score).permit(:point_q1, :point_q2, :point_q3, :point_q4, :point_op_q1, :point_op_q2, :point_op_q3, :point_op_q4)
    end

    def oppo_params
      params.require(:game).permit(:opponent)
    end



  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController

  def show
    @game = Game.find(params[:id])
    @playbyplayscore = Score.new
    add_breadcrumb "Home", home_path, :title => "Home"
    add_breadcrumb "Game Result", results_path, :title => "Game Result"
    add_breadcrumb "vs #{@game.opponent_name}", game_path(@game), :title => "Opponent"

  end

end

app/helpers/games_helper.rb
module GamesHelper
  def team_stat_class(num1, num2)
    if num1>num2
      'advantage'
    elsif num1<num2
      'disadvantage'
    else
      'even'
    end

  end
end

app/views/admin/games/dnp.html.erb
<h1>DNP List</h1>

<section>
  <ul>
    <li>Game ID: <%= @game.id %> </li>
    <li>Game Oppo: <%= @game.opponent_name %></li>
  </ul>
</section>

<section>
  <h3>DNP List</h3>
  <% if @outgame.blank? %>
    GOOD, no one is in DNP list
  <% else %>
    <ul>
    <% @outgame.each do |playerstat| %>
      <li><%=playerstat.player.name %>, <%= link_to 'Remove', admin_game_remove_dnp_path(playerstat.game_id, playerstat.player_id)%></li>
    <% end %>
    </ul>
  <% end %>
</section>

<section>
  <h3>In-Game Players</h3>
  <ul>
  <% @ingame.each do |playerstat| %>
    <li><%=playerstat.player.name %>, <%= link_to 'Add To DNP', admin_game_add_dnp_path(playerstat.game_id, playerstat.player_id)%></li>
  <% end %>
  </ul>
</section>

app/views/admin/games/edit.html.erb
<section>
    <h1>Game ID: <%= @game.id %> </h1>
    <%= form_for :game, url: admin_update_game_path, method: :patch do |f| %>
      <%= f.label :opponent %>

      <%= f.select(:opponent) do %>
        <% opp_array = OPPO_TEAM_ARR.map.with_index { |oppo, index| [oppo[:name], index + 1]} %>
        <%= options_for_select(opp_array) %>
      <% end %>

      <%= f.label :gametime %>
      <%= f.datetime_local_field :gametime, value: @game.gametime %>

      <%= f.hidden_field :season_id, value: @game.season_id %>

      <%= f.submit("UPDATE") %>
    <% end %>
    <%= link_to 'Cancel', admin_season_path(@game.season) %>
</section>

app/views/admin/games/score_only.html.erb
<h1>Only Score?</h1>
<div>
  <%= link_to 'back to game', admin_game_path(params[:id])  %>
</div>
<%= form_tag(admin_game_score_only_update_path, method: "post") do %>
<section>
  <!-- Switch -->
  <div class="switch">
    <label>
      <input type="checkbox" id="score_only_checkbox" name='score_only_checkbox'>
      <span class="lever"></span>
      Score Only?
    </label>
  </div>
</section>

<section id='score_only_field' class='margin-top-lg hide'>

  <% @playerstats.each do |playerstat| %>
    <% unless (playerstat.dnp && !playerstat.score_only)  %>
    <div>
      <%= label_tag('score['+playerstat.player_id.to_s+']', playerstat.player.name) %>
      <%= text_field_tag 'score['+playerstat.player_id.to_s+']', playerstat.score_only_score   %>

    </div>
    <% end %>
  <% end %>
</section>
  <button type="submit" name="button" class="margin-all">Update</button>


  <% end %>

app/views/admin/games/show.html.erb
<h1><%= @game.opponent_name %></h1>
<% if @game.opponent_name == "TBD" %>
<%# When opponent is not selected, have to choose one opponent first %>
  <section>
    <ul>
      <li>Game ID: <%= @game.id %> </li>
      <li>Game Oppo: <%= @game.opponent_name %></li>
      <%= form_for :game, url: admin_game_update_oppo_path do |f| %>
        <%= f.select(:opponent) do %>
          <% opp_array = OPPO_TEAM_ARR[0..-2].map.with_index { |oppo, index| [oppo[:name], index + 1]} %>
          <%= options_for_select(opp_array) %>
        <% end %>
        <%= f.submit("Update") %>
      <% end %>
    </ul>
  </section>
<% else %>

<div class="row">
  <div class="col s12">
    <h3>Recording Quarter: <%= recording_quater(@score.recording_quarter) %></h3>
    <% unless @score.end_recording? %>
      <%= link_to 'Quarter End', admin_quarter_end_path(@game), method: 'get'%><br>
    <% end %>
  </div>
</div>
<div class="row">
  <%= form_for :move, url: admin_create_action_path do |f| %>

  <section class='admin-game-form game__section col s12'>
    <h4>Add Action</h4>
      <%= f.submit %> (TIPS: `Shift` + `Enter` to submit)
      <div>
        <h5>Choose player</h5>

        <% @player_collection.order(:number).each_with_index do |player, idx|
          idxplus = idx + 1
          classText =  'playerkey' + idxplus.to_s %>
          <label for="move_player_id_<%=player.id%>" class=<%= classText%>>
            <%= f.radio_button :player_id, player.id %>
            <span><%= "#{player.name} (#{idxplus})" %></span>
          </label>
        <% end %>

        <label for='move_player_id_0'>
          <%= f.radio_button :player_id, TEAM_ID %>
          <span>TEAM (-)</span>
        </label>
        <label for='move_player_id_-1'>
          <%= f.radio_button :player_id, OPPO_TEAM_ID %>
          <span>OPPO (+)</span>
        </label>
      </div>

      <div>
        <h5>Choose action</h5>
        <% GAME_ACTION_LIST.each_with_index do |val,index| %>
          <label id='key-<%= val[:keyindex]%>'>
            <%= f.radio_button :action_index, index %> <span><%= val[:name] %> (<%= val[:key] %>)</span>
          </label>
        <% end %>
      </div>

      <div>Description: <%= f.text_field :description, placeholder: 'OPTIONAL'%></div>

      <%= f.hidden_field :game_id, value: @game.id %>
      <%= f.hidden_field :quarter, value: @score.recording_quarter %>


  </section>

  <section class="game__section col s12">
    <h4>Action List</h4>
    <div>Insert Position:<%= f.text_field :position, value: cookies[:insert_position] %> Clear if adding to the end of list</div>
    <div class="game__action-list">
      <% @action_list.sort_by{|e| -e[:id]}.each do |action| %>
        <%# MOVE SECTION SHOULD BE CREATED on-the-fly%>
        <div class="game__action-item">
          <span>Pos: <%= action.position %></span>
          <span class="player">Player: <%= action.player_name %></span>
          <span class="action">Action: <%=action_from_index(action.action_index)%></span>
          <span>CTAs: <%= link_to 'Move Up', admin_action_move_postion_path(action.id,'moveup')%>, <%= link_to 'Move Down', admin_action_move_postion_path(action.id,'movedown')%>, <%= link_to 'Remove', admin_delete_action_path(action), method: :delete, data: { confirm: 'Are you sure?' } %></span>
          <% if action.description && action.description.length > 0 %><span>Description: <%= action.description%></span><% end %>
        </div>
      <% end %>
    </div>

  </section>
  <% end %>

</div>

<div class="row">
  <section class="game__section col m6">
    <h4>CTAs</h4>
    <ul>
      <li>
        <p>Migrate data from actions to player stat, team stat, oppo stat. Click when action recording is done.</p>
        <%= link_to 'Migrate', admin_game_stat_migrate_path(@game), method: 'get'%>
      </li>
      <li>
        <p>After Migration above, you can update players to DNP</p>
        <%= link_to 'DNP Manage', admin_game_dnp_path(@game.id)%>
      </li>
      <li>
        <p>When only having score for players, click here.</p>
        <%= link_to 'Only Score', admin_game_score_only_path(@game.id)%>
      </li>
    </ul>
  </section>
  <section class="game__section col m6">
    <h4>Score</h4>
    <p>This section should be updated by entering actions, but can be overwriten manually.</p>
    <%= form_for @score, url: admin_game_update_score_path, method: 'post' do |f| %>
    <table>
      <thead>
        <td>Team</td>
        <td>Q1</td>
        <td>Q2</td>
        <td>Q3</td>
        <td>Q4</td>
        <td>Total</td>
      </thead>
      <tbody>
        <tr>
          <td>LSJ</td>
          <td width='80px'><%= f.text_field :point_q1, class: 'small-text-field' %></td>
          <td width='80px'><%= f.text_field :point_q2, class: 'small-text-field' %></td>
          <td width='80px'><%= f.text_field :point_q3, class: 'small-text-field' %></td>
          <td width='80px'><%= f.text_field :point_q4, class: 'small-text-field' %></td>
          <td><%= @score.point_total %></td>
        </tr>
        <tr>
          <td><%= @game.opponent_name %></td>
          <td width='80px'><%= f.text_field :point_op_q1, class: 'small-text-field' %></td>
          <td width='80px'><%= f.text_field :point_op_q2, class: 'small-text-field' %></td>
          <td width='80px'><%= f.text_field :point_op_q3, class: 'small-text-field' %></td>
          <td width='80px'><%= f.text_field :point_op_q4, class: 'small-text-field' %></td>
          <td><%= @score.point_op_total %></td>
        </tr>
      </tbody>
    </table>
    <%= f.submit %>
    <% end %>
  </section>
</div>

<% end %>